import type { ImageSourcePropType } from "react-native";

/**
 * Generated from local Anky companion frame assets.
 *
 * React Native bundlers need static require(...) calls for local images.
 * Do not replace this with require(dynamicPath).
 */
export const ANKY_FRAMES = {
  1: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_001.png"),
  2: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_002.png"),
  3: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_003.png"),
  4: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_004.png"),
  5: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_005.png"),
  6: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_006.png"),
  7: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_007.png"),
  8: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_008.png"),
  9: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_009.png"),
  10: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_010.png"),
  11: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_011.png"),
  12: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_012.png"),
  13: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_013.png"),
  14: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_014.png"),
  15: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_015.png"),
  16: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_016.png"),
  17: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_017.png"),
  18: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_018.png"),
  19: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_019.png"),
  20: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_020.png"),
  21: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_021.png"),
  22: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_022.png"),
  23: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_023.png"),
  24: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_024.png"),
  25: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_025.png"),
  26: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_026.png"),
  27: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_027.png"),
  28: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_028.png"),
  29: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_029.png"),
  30: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_030.png"),
  31: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_031.png"),
  32: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_032.png"),
  33: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_033.png"),
  34: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_034.png"),
  35: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_035.png"),
  36: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_036.png"),
  37: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_037.png"),
  38: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_038.png"),
  39: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_039.png"),
  40: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_040.png"),
  41: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_041.png"),
  42: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_042.png"),
  43: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_043.png"),
  44: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_044.png"),
  45: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_045.png"),
  46: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_046.png"),
  47: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_047.png"),
  48: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_048.png"),
  49: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_049.png"),
  50: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_050.png"),
  51: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_051.png"),
  52: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_052.png"),
  53: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_053.png"),
  54: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_054.png"),
  55: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_055.png"),
  56: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_056.png"),
  57: require("../../assets/anky-animation/assets/anky/frames/normalized/frame_057.png"),
  thread_001: require("../../assets/anky-companion-thread/frames/thread_001.png"),
  thread_002: require("../../assets/anky-companion-thread/frames/thread_002.png"),
  thread_003: require("../../assets/anky-companion-thread/frames/thread_003.png"),
  thread_004: require("../../assets/anky-companion-thread/frames/thread_004.png"),
  thread_005: require("../../assets/anky-companion-thread/frames/thread_005.png"),
  thread_006: require("../../assets/anky-companion-thread/frames/thread_006.png"),
  thread_007: require("../../assets/anky-companion-thread/frames/thread_007.png"),
  thread_008: require("../../assets/anky-companion-thread/frames/thread_008.png"),
} as const satisfies Record<string | number, ImageSourcePropType>;

export type AnkyFrameId = keyof typeof ANKY_FRAMES;
